-- WealthPulse Supabase schema initialization
-- Generated by concatenating repository migrations in timestamp order.
-- Run this on a fresh Supabase project from the SQL Editor.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Migration: 20260223021937_b89a467f-1a7a-4c9a-97ff-c280e390c147.sql
CREATE TABLE public.investments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  asset_class TEXT NOT NULL,
  asset_name TEXT NOT NULL,
  ticker_symbol TEXT,
  quantity NUMERIC,
  invested_value NUMERIC NOT NULL DEFAULT 0,
  current_value NUMERIC NOT NULL DEFAULT 0,
  current_price NUMERIC,
  api_connected BOOLEAN NOT NULL DEFAULT false,
  notes TEXT,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  last_price_update TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE public.bank_accounts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bank_name TEXT NOT NULL,
  account_type TEXT NOT NULL DEFAULT 'Savings',
  balance NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE public.expenses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL,
  expense_group TEXT NOT NULL DEFAULT 'Short',
  payment_method TEXT,
  description TEXT,
  is_recurring BOOLEAN NOT NULL DEFAULT false,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE public.liabilities (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  liability_type TEXT NOT NULL,
  outstanding_amount NUMERIC NOT NULL DEFAULT 0,
  monthly_payment NUMERIC NOT NULL DEFAULT 0,
  interest_rate NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE public.profiles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  currency TEXT NOT NULL DEFAULT 'INR',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own investments" ON public.investments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own investments" ON public.investments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own investments" ON public.investments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own investments" ON public.investments FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own bank_accounts" ON public.bank_accounts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own bank_accounts" ON public.bank_accounts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own bank_accounts" ON public.bank_accounts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own bank_accounts" ON public.bank_accounts FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own expenses" ON public.expenses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own expenses" ON public.expenses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own expenses" ON public.expenses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own expenses" ON public.expenses FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own liabilities" ON public.liabilities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liabilities" ON public.liabilities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liabilities" ON public.liabilities FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liabilities" ON public.liabilities FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Migration: 20260224003935_a2c17d48-23bd-43ae-b2db-f53f11202067.sql
ALTER TABLE public.investments ADD COLUMN avg_buy_price numeric NULL;

-- Migration: 20260224033922_0ec68534-1197-443f-a3c4-2ef10686ea2c.sql
ALTER TABLE public.investments
  ADD COLUMN currency text NOT NULL DEFAULT 'INR',
  ADD COLUMN fx_rate numeric NULL,
  ADD COLUMN base_currency_value numeric NOT NULL DEFAULT 0;

UPDATE public.investments SET base_currency_value = current_value, fx_rate = 1.0 WHERE currency = 'INR';

-- Migration: 20260224040740_4a25cfe5-7f4e-4963-a3a2-5390fc27f037.sql
ALTER TABLE public.bank_accounts
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS fx_rate numeric NULL,
  ADD COLUMN IF NOT EXISTS base_currency_value numeric NOT NULL DEFAULT 0;

ALTER TABLE public.expenses
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS fx_rate numeric NULL,
  ADD COLUMN IF NOT EXISTS base_currency_value numeric NOT NULL DEFAULT 0;

ALTER TABLE public.liabilities
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS fx_rate numeric NULL,
  ADD COLUMN IF NOT EXISTS base_currency_value numeric NOT NULL DEFAULT 0;

UPDATE public.bank_accounts SET base_currency_value = balance, fx_rate = 1 WHERE fx_rate IS NULL;
UPDATE public.expenses SET base_currency_value = amount, fx_rate = 1 WHERE fx_rate IS NULL;
UPDATE public.liabilities SET base_currency_value = outstanding_amount, fx_rate = 1 WHERE fx_rate IS NULL;

-- Migration: 20260224050659_949c2b6a-5b00-4edc-a4bb-c133e0de0d1e.sql
CREATE TABLE public.investment_transactions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  investment_id UUID REFERENCES public.investments(id) ON DELETE CASCADE,
  ticker_symbol TEXT,
  asset_class TEXT NOT NULL,
  asset_name TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 0,
  buy_price NUMERIC NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  fx_rate_at_purchase NUMERIC,
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  transaction_type TEXT NOT NULL DEFAULT 'buy',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.investment_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own transactions"
  ON public.investment_transactions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own transactions"
  ON public.investment_transactions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own transactions"
  ON public.investment_transactions FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own transactions"
  ON public.investment_transactions FOR DELETE
  USING (auth.uid() = user_id);

INSERT INTO public.investment_transactions (
  user_id, investment_id, ticker_symbol, asset_class, asset_name,
  quantity, buy_price, currency, fx_rate_at_purchase, transaction_date, transaction_type
)
SELECT
  i.user_id,
  i.id,
  i.ticker_symbol,
  i.asset_class,
  i.asset_name,
  COALESCE(i.quantity, 1),
  COALESCE(i.avg_buy_price, i.invested_value),
  i.currency,
  i.fx_rate,
  COALESCE(i.created_at::date, CURRENT_DATE),
  'buy'
FROM public.investments i
WHERE i.api_connected = true AND i.quantity IS NOT NULL AND i.quantity > 0;

-- Migration: 20260303083316_7ab0efbe-8b52-4184-b329-2d3843d90145.sql
CREATE TABLE public.bank_transactions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  bank_account_id UUID NOT NULL REFERENCES public.bank_accounts(id) ON DELETE CASCADE,
  linked_expense_id UUID REFERENCES public.expenses(id) ON DELETE SET NULL,
  transaction_type TEXT NOT NULL DEFAULT 'DEBIT',
  amount NUMERIC NOT NULL DEFAULT 0,
  description TEXT,
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own bank_transactions"
ON public.bank_transactions FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own bank_transactions"
ON public.bank_transactions FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own bank_transactions"
ON public.bank_transactions FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own bank_transactions"
ON public.bank_transactions FOR DELETE
USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.create_expense_with_deduction(
  p_user_id UUID,
  p_amount NUMERIC,
  p_category TEXT,
  p_expense_group TEXT,
  p_payment_method TEXT,
  p_description TEXT,
  p_date DATE,
  p_is_recurring BOOLEAN,
  p_currency TEXT,
  p_fx_rate NUMERIC,
  p_base_currency_value NUMERIC,
  p_bank_account_id UUID DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_expense_id UUID;
  v_balance NUMERIC;
  v_account_currency TEXT;
BEGIN
  IF p_bank_account_id IS NOT NULL THEN
    SELECT balance, currency INTO v_balance, v_account_currency
    FROM public.bank_accounts
    WHERE id = p_bank_account_id AND user_id = p_user_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RETURN json_build_object('success', false, 'error', 'Bank account not found');
    END IF;

    IF v_balance < p_amount THEN
      RETURN json_build_object('success', false, 'error', 'Insufficient balance');
    END IF;
  END IF;

  INSERT INTO public.expenses (user_id, amount, category, expense_group, payment_method, description, date, is_recurring, currency, fx_rate, base_currency_value)
  VALUES (p_user_id, p_amount, p_category, p_expense_group, p_payment_method, p_description, p_date, p_is_recurring, p_currency, p_fx_rate, p_base_currency_value)
  RETURNING id INTO v_expense_id;

  IF p_bank_account_id IS NOT NULL THEN
    UPDATE public.bank_accounts
    SET balance = balance - p_amount,
        base_currency_value = (balance - p_amount) * COALESCE(fx_rate, 1)
    WHERE id = p_bank_account_id AND user_id = p_user_id;

    INSERT INTO public.bank_transactions (user_id, bank_account_id, linked_expense_id, transaction_type, amount, description, transaction_date)
    VALUES (p_user_id, p_bank_account_id, v_expense_id, 'DEBIT', p_amount, p_description, p_date);
  END IF;

  RETURN json_build_object('success', true, 'expense_id', v_expense_id);
END;
$$;

-- Migration: 20260308174346_67fe111f-3364-4156-9a43-2def6e7fbc42.sql
CREATE TABLE public.income_entries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  source_name TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'INR',
  fx_rate NUMERIC,
  base_currency_value NUMERIC NOT NULL DEFAULT 0,
  frequency TEXT NOT NULL DEFAULT 'Monthly',
  date_received DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.income_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own income_entries" ON public.income_entries FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own income_entries" ON public.income_entries FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own income_entries" ON public.income_entries FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own income_entries" ON public.income_entries FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Migration: 20260308192902_135481ef-48ed-48d0-baa7-839f8361e9a3.sql
CREATE TABLE public.stocks_metadata (
  ticker TEXT NOT NULL PRIMARY KEY,
  company_name TEXT NOT NULL DEFAULT '',
  sector TEXT NOT NULL DEFAULT 'Other',
  industry TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'USD',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.stocks_metadata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated can read stocks_metadata"
  ON public.stocks_metadata FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Anyone authenticated can insert stocks_metadata"
  ON public.stocks_metadata FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Anyone authenticated can update stocks_metadata"
  ON public.stocks_metadata FOR UPDATE TO authenticated
  USING (true);

-- Migration: 20260308230009_5167a4c6-8d9c-495d-99ea-43a944a7016e.sql
ALTER TABLE public.stocks_metadata ALTER COLUMN sector SET DEFAULT 'Unclassified';

-- Migration: 20260310101137_b0a555e2-0ca2-425c-b20a-b5b77e1959d9.sql
ALTER TABLE public.liabilities
  ADD COLUMN IF NOT EXISTS original_loan_amount numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loan_tenure_months integer,
  ADD COLUMN IF NOT EXISTS loan_start_date date,
  ADD COLUMN IF NOT EXISTS lender_name text;

-- Migration: 20260311000411_2f41d9b1-03af-4bee-88c1-7eff0fef13d6.sql
ALTER TABLE public.liabilities
ADD COLUMN IF NOT EXISTS credit_limit numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS min_payment_percent numeric DEFAULT 5;

-- Migration: 20260313000000_normalize_financial_rls.sql
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liabilities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "Users can insert own bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "Users can update own bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "Users can delete own bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "Users manage their own data" ON public.bank_accounts;

CREATE POLICY "Users manage their own data"
ON public.bank_accounts
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "Users can insert own bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "Users can update own bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "Users can delete own bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "Users manage their own data" ON public.bank_transactions;

CREATE POLICY "Users manage their own data"
ON public.bank_transactions
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own investments" ON public.investments;
DROP POLICY IF EXISTS "Users can insert own investments" ON public.investments;
DROP POLICY IF EXISTS "Users can update own investments" ON public.investments;
DROP POLICY IF EXISTS "Users can delete own investments" ON public.investments;
DROP POLICY IF EXISTS "Users manage their own data" ON public.investments;

CREATE POLICY "Users manage their own data"
ON public.investments
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own transactions" ON public.investment_transactions;
DROP POLICY IF EXISTS "Users can insert own transactions" ON public.investment_transactions;
DROP POLICY IF EXISTS "Users can update own transactions" ON public.investment_transactions;
DROP POLICY IF EXISTS "Users can delete own transactions" ON public.investment_transactions;
DROP POLICY IF EXISTS "Users manage their own data" ON public.investment_transactions;

CREATE POLICY "Users manage their own data"
ON public.investment_transactions
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users manage their own data" ON public.expenses;

CREATE POLICY "Users manage their own data"
ON public.expenses
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own income_entries" ON public.income_entries;
DROP POLICY IF EXISTS "Users can insert own income_entries" ON public.income_entries;
DROP POLICY IF EXISTS "Users can update own income_entries" ON public.income_entries;
DROP POLICY IF EXISTS "Users can delete own income_entries" ON public.income_entries;
DROP POLICY IF EXISTS "Users manage their own data" ON public.income_entries;

CREATE POLICY "Users manage their own data"
ON public.income_entries
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can insert own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can update own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can delete own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users manage their own data" ON public.liabilities;

CREATE POLICY "Users manage their own data"
ON public.liabilities
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Migration: 20260315053000_make_investments_current_value_nullable.sql
ALTER TABLE public.investments
ALTER COLUMN current_value DROP NOT NULL;

ALTER TABLE public.investments
ALTER COLUMN current_value DROP DEFAULT;

-- Migration: 20260315060000_add_investment_price_tracking.sql
ALTER TABLE public.investments
ADD COLUMN IF NOT EXISTS current_price numeric,
ADD COLUMN IF NOT EXISTS last_price_update timestamp with time zone;

-- Migration: 20260319083000_add_normalized_investment_import.sql
ALTER TABLE public.investments
  ADD COLUMN IF NOT EXISTS asset_type text NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.investment_transactions
  ADD COLUMN IF NOT EXISTS asset_type text NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.investments
SET asset_type = CASE
  WHEN asset_class IN ('US Stocks', 'Indian Stocks', 'ESOPs / RSUs') THEN 'equities'
  WHEN asset_class IN ('Mutual Funds', 'Global Funds') THEN 'mutual_funds'
  WHEN asset_class = 'Crypto' THEN 'crypto'
  WHEN asset_class = 'Fixed Deposits' THEN 'fixed_deposits'
  WHEN asset_class = 'Commodities' THEN 'gold'
  WHEN asset_class IN ('Bonds', 'PPF', 'NPS') THEN 'bonds'
  ELSE 'other'
END
WHERE asset_type = 'other';

UPDATE public.investment_transactions
SET asset_type = CASE
  WHEN asset_class IN ('US Stocks', 'Indian Stocks', 'ESOPs / RSUs') THEN 'equities'
  WHEN asset_class IN ('Mutual Funds', 'Global Funds') THEN 'mutual_funds'
  WHEN asset_class = 'Crypto' THEN 'crypto'
  WHEN asset_class = 'Fixed Deposits' THEN 'fixed_deposits'
  WHEN asset_class = 'Commodities' THEN 'gold'
  WHEN asset_class IN ('Bonds', 'PPF', 'NPS') THEN 'bonds'
  ELSE 'other'
END
WHERE asset_type = 'other';

ALTER TABLE public.investments
  DROP CONSTRAINT IF EXISTS investments_asset_type_check,
  DROP CONSTRAINT IF EXISTS investments_metadata_is_object;

ALTER TABLE public.investment_transactions
  DROP CONSTRAINT IF EXISTS investment_transactions_asset_type_check,
  DROP CONSTRAINT IF EXISTS investment_transactions_metadata_is_object;

ALTER TABLE public.investments
  ADD CONSTRAINT investments_asset_type_check
    CHECK (asset_type IN ('equities', 'mutual_funds', 'crypto', 'fixed_deposits', 'gold', 'bonds', 'other')),
  ADD CONSTRAINT investments_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object');

ALTER TABLE public.investment_transactions
  ADD CONSTRAINT investment_transactions_asset_type_check
    CHECK (asset_type IN ('equities', 'mutual_funds', 'crypto', 'fixed_deposits', 'gold', 'bonds', 'other')),
  ADD CONSTRAINT investment_transactions_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object');

CREATE OR REPLACE FUNCTION public.import_investment_record(
  p_user_id uuid,
  p_asset_type text,
  p_name text,
  p_quantity numeric,
  p_unit_price numeric,
  p_total_value numeric,
  p_currency text,
  p_date date,
  p_metadata jsonb DEFAULT '{}'::jsonb,
  p_ticker_symbol text DEFAULT NULL,
  p_fx_rate numeric DEFAULT 1,
  p_base_currency_value numeric DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  v_asset_type text := lower(trim(coalesce(p_asset_type, '')));
  v_currency text := upper(trim(coalesce(p_currency, '')));
  v_name text := trim(coalesce(p_name, ''));
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_asset_class text;
  v_api_connected boolean;
  v_ticker_symbol text;
  v_investment_id uuid;
  v_existing_qty numeric;
  v_existing_invested numeric;
  v_existing_base numeric;
  v_total_value numeric := coalesce(p_total_value, p_quantity * p_unit_price);
  v_base_currency_value numeric := coalesce(p_base_currency_value, coalesce(p_total_value, p_quantity * p_unit_price) * coalesce(p_fx_rate, 1));
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'Unauthorized import request';
  END IF;

  IF v_asset_type NOT IN ('equities', 'mutual_funds', 'crypto', 'fixed_deposits', 'gold', 'bonds', 'other') THEN
    RAISE EXCEPTION 'Unsupported asset_type: %', p_asset_type;
  END IF;

  IF jsonb_typeof(v_metadata) <> 'object' THEN
    RAISE EXCEPTION 'Metadata must be a JSON object';
  END IF;

  IF v_name = '' THEN
    RAISE EXCEPTION 'Asset name is required';
  END IF;

  IF p_date IS NULL THEN
    RAISE EXCEPTION 'Transaction date is required';
  END IF;

  IF coalesce(p_quantity, 0) <= 0 THEN
    RAISE EXCEPTION 'Quantity must be greater than 0';
  END IF;

  IF coalesce(p_unit_price, 0) <= 0 THEN
    RAISE EXCEPTION 'Unit price must be greater than 0';
  END IF;

  IF coalesce(v_total_value, 0) <= 0 THEN
    RAISE EXCEPTION 'Total value must be greater than 0';
  END IF;

  IF v_currency = '' THEN
    RAISE EXCEPTION 'Currency is required';
  END IF;

  CASE v_asset_type
    WHEN 'equities' THEN
      v_asset_class := CASE
        WHEN upper(coalesce(p_ticker_symbol, '')) ~ '(\.NS|\.BO)$' OR v_currency = 'INR' THEN 'Indian Stocks'
        ELSE 'US Stocks'
      END;
      v_api_connected := true;
      IF trim(coalesce(p_ticker_symbol, '')) = '' THEN
        RAISE EXCEPTION 'Equities require ticker_symbol';
      END IF;
    WHEN 'mutual_funds' THEN
      v_asset_class := 'Mutual Funds';
      v_api_connected := false;
      IF NOT (v_metadata ? 'fund_name' OR v_metadata ? 'isin') THEN
        RAISE EXCEPTION 'Mutual funds require fund_name or isin in metadata';
      END IF;
    WHEN 'crypto' THEN
      v_asset_class := 'Crypto';
      v_api_connected := true;
      IF trim(coalesce(p_ticker_symbol, '')) = '' THEN
        RAISE EXCEPTION 'Crypto imports require ticker_symbol';
      END IF;
    WHEN 'fixed_deposits' THEN
      v_asset_class := 'Fixed Deposits';
      v_api_connected := false;
      IF NOT (v_metadata ? 'interest_rate' AND v_metadata ? 'start_date' AND v_metadata ? 'maturity_date') THEN
        RAISE EXCEPTION 'Fixed deposits require interest_rate, start_date, and maturity_date';
      END IF;
    WHEN 'gold' THEN
      v_asset_class := 'Commodities';
      v_api_connected := false;
      IF NOT (v_metadata ? 'type') THEN
        RAISE EXCEPTION 'Gold imports require type';
      END IF;
    WHEN 'bonds' THEN
      v_asset_class := 'Bonds';
      v_api_connected := false;
      IF NOT (v_metadata ? 'coupon_rate' AND v_metadata ? 'maturity_date' AND v_metadata ? 'face_value') THEN
        RAISE EXCEPTION 'Bonds require coupon_rate, maturity_date, and face_value';
      END IF;
    ELSE
      v_asset_class := 'Custom Asset';
      v_api_connected := false;
  END CASE;

  v_ticker_symbol := NULLIF(trim(coalesce(p_ticker_symbol, '')), '');

  IF v_asset_type = 'equities' AND v_ticker_symbol IS NOT NULL THEN
    v_ticker_symbol := upper(v_ticker_symbol);
  ELSIF v_asset_type = 'crypto' AND v_ticker_symbol IS NOT NULL THEN
    v_ticker_symbol := upper(v_ticker_symbol);
    IF right(v_ticker_symbol, 4) <> '-USD' THEN
      v_ticker_symbol := regexp_replace(v_ticker_symbol, '-USD$', '') || '-USD';
    END IF;
  END IF;

  IF v_api_connected AND v_ticker_symbol IS NOT NULL THEN
    SELECT id, coalesce(quantity, 0), coalesce(invested_value, 0), coalesce(base_currency_value, 0)
    INTO v_investment_id, v_existing_qty, v_existing_invested, v_existing_base
    FROM public.investments
    WHERE user_id = p_user_id
      AND ticker_symbol = v_ticker_symbol
    LIMIT 1;

    IF v_investment_id IS NULL THEN
      INSERT INTO public.investments (
        user_id,
        asset_type,
        asset_class,
        asset_name,
        ticker_symbol,
        quantity,
        avg_buy_price,
        invested_value,
        current_value,
        current_price,
        api_connected,
        currency,
        fx_rate,
        base_currency_value,
        last_updated,
        last_price_update,
        metadata
      )
      VALUES (
        p_user_id,
        v_asset_type,
        v_asset_class,
        v_name,
        v_ticker_symbol,
        p_quantity,
        p_unit_price,
        v_total_value,
        NULL,
        NULL,
        true,
        v_currency,
        p_fx_rate,
        v_base_currency_value,
        now(),
        NULL,
        v_metadata
      )
      RETURNING id INTO v_investment_id;
    ELSE
      UPDATE public.investments
      SET
        asset_type = v_asset_type,
        asset_class = v_asset_class,
        asset_name = COALESCE(NULLIF(asset_name, ''), v_name),
        quantity = coalesce(quantity, 0) + p_quantity,
        invested_value = coalesce(invested_value, 0) + v_total_value,
        base_currency_value = coalesce(base_currency_value, 0) + v_base_currency_value,
        avg_buy_price = CASE
          WHEN coalesce(quantity, 0) + p_quantity > 0
            THEN (coalesce(invested_value, 0) + v_total_value) / (coalesce(quantity, 0) + p_quantity)
          ELSE p_unit_price
        END,
        currency = v_currency,
        fx_rate = p_fx_rate,
        last_updated = now(),
        metadata = coalesce(metadata, '{}'::jsonb) || v_metadata
      WHERE id = v_investment_id;
    END IF;
  ELSE
    INSERT INTO public.investments (
      user_id,
      asset_type,
      asset_class,
      asset_name,
      ticker_symbol,
      quantity,
      avg_buy_price,
      invested_value,
      current_value,
      current_price,
      api_connected,
      currency,
      fx_rate,
      base_currency_value,
      last_updated,
      last_price_update,
      metadata
    )
    VALUES (
      p_user_id,
      v_asset_type,
      v_asset_class,
      v_name,
      v_ticker_symbol,
      p_quantity,
      p_unit_price,
      v_total_value,
      v_total_value,
      NULL,
      false,
      v_currency,
      p_fx_rate,
      v_base_currency_value,
      now(),
      NULL,
      v_metadata
    )
    RETURNING id INTO v_investment_id;
  END IF;

  INSERT INTO public.investment_transactions (
    user_id,
    investment_id,
    ticker_symbol,
    asset_type,
    asset_class,
    asset_name,
    quantity,
    buy_price,
    currency,
    fx_rate_at_purchase,
    transaction_date,
    transaction_type,
    metadata
  )
  VALUES (
    p_user_id,
    v_investment_id,
    v_ticker_symbol,
    v_asset_type,
    v_asset_class,
    v_name,
    p_quantity,
    p_unit_price,
    v_currency,
    p_fx_rate,
    p_date,
    'buy',
    v_metadata
  );

  RETURN v_investment_id;
END;
$$;

COMMIT;
